[package]
name = "Neatify"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
walkdir = "2.3.2"
regex = "1.5.4"
lazy_static = "1.4.0"
colored = "2.0.0"
